name: ddenv
dependencies:
  - pip 
  - python=3.8.10
  - pip:
      - python-dotenv==0.19.0
      - langchain==0.0.263
      - openai==0.27.8
      - pypdf==3.15.1
      - googletrans==3.1.0a0
      - openpyxl==3.1.2
      - PyPDF2==3.0.1
      - chromadb==0.4.10
      - tiktoken==0.5.1
      - faiss-cpu==1.7.1
